import {
  MenuItem,
  MenuItemLegacy,
  MenuCategoryModel,
  MenuCategory,
  Badge,
  Currency,
  Origin,
  DrawType,
  Intensity,
  FlavorType,
  Strength,
  DrinkType,
  AlcoholContent,
  DietaryType,
} from './menu-item.model';

export const MENU_CATEGORIES: MenuCategoryModel[] = [
  new MenuCategoryModel(MenuCategory.Cachimbas, 'pages.menu.categories.cachimbas', '💨', 1),
  new MenuCategoryModel(MenuCategory.Sabores, 'pages.menu.categories.sabores', '🌿', 2),
  new MenuCategoryModel(MenuCategory.Bebidas, 'pages.menu.categories.bebidas', '🍹', 3),
  new MenuCategoryModel(MenuCategory.Cocteles, 'pages.menu.categories.cocteles', '🍸', 4),
  new MenuCategoryModel(MenuCategory.Comida, 'pages.menu.categories.comida', '🍽️', 5),
];

export const CACHIMBAS: MenuItem[] = [
  new MenuItemLegacy(
    'h1',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.aeonEdition.name',
    45,
    Currency.EUR,
    'pages.menu.cachimbas.items.aeonEdition.description',
    'aeon-edition.jpg',
    Badge.Signature,
    Origin.Alemania,
    DrawType.Abierto,
    Intensity.Signature
  ),
  new MenuItemLegacy(
    'h2',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.khalilMamoon.name',
    35,
    Currency.EUR,
    'pages.menu.cachimbas.items.khalilMamoon.description',
    'khalil-mamoon.jpg',
    Badge.Premium,
    Origin.Egipto,
    DrawType.Cerrado,
    Intensity.Premium
  ),
  new MenuItemLegacy(
    'h3',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.steamulation.name',
    50,
    Currency.EUR,
    'pages.menu.cachimbas.items.steamulation.description',
    'steamulation.jpg',
    Badge.Signature,
    Origin.Alemania,
    DrawType.Abierto,
    Intensity.Signature
  ),
  new MenuItemLegacy(
    'h4',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.moze.name',
    40,
    Currency.EUR,
    'pages.menu.cachimbas.items.moze.description',
    'moze.jpg',
    undefined,
    Origin.Alemania,
    DrawType.Medio,
    Intensity.Premium
  ),
  new MenuItemLegacy(
    'h5',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.oblako.name',
    38,
    Currency.EUR,
    'pages.menu.cachimbas.items.oblako.description',
    'oblako.jpg',
    undefined,
    Origin.Rusia,
    DrawType.Medio,
    Intensity.Premium
  ),
  new MenuItemLegacy(
    'h6',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.maklaud.name',
    30,
    Currency.EUR,
    'pages.menu.cachimbas.items.maklaud.description',
    'maklaud.jpg',
    undefined,
    Origin.Rusia,
    DrawType.Medio,
    Intensity.Standard
  ),
  new MenuItemLegacy(
    'h7',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.wookah.name',
    42,
    Currency.EUR,
    'pages.menu.cachimbas.items.wookah.description',
    'wookah.jpg',
    Badge.New,
    Origin.Espana,
    DrawType.Abierto,
    Intensity.Premium
  ),
  new MenuItemLegacy(
    'h8',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.japona.name',
    32,
    Currency.EUR,
    'pages.menu.cachimbas.items.japona.description',
    'japona.jpg',
    undefined,
    Origin.Espana,
    DrawType.Medio,
    Intensity.Standard
  ),
  new MenuItemLegacy(
    'h9',
    MenuCategory.Cachimbas,
    'pages.menu.cachimbas.items.классический.name',
    25,
    Currency.EUR,
    'pages.menu.cachimbas.items.классический.description',
    'klassicheskiy.jpg',
    undefined,
    Origin.Rusia,
    DrawType.Cerrado,
    Intensity.Standard
  ),
];

export const SABORES: MenuItem[] = [
  new MenuItemLegacy(
    's1',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.doubleMint.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.doubleMint.description',
    undefined,
    Badge.Popular,
    undefined, undefined, undefined,
    FlavorType.Mentolado,
    Strength.Fuerte
  ),
  new MenuItemLegacy(
    's2',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.watermelon.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.watermelon.description',
    undefined,
    Badge.Popular,
    undefined, undefined, undefined,
    FlavorType.Frutal,
    Strength.Suave
  ),
  new MenuItemLegacy(
    's3',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.spicedApple.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.spicedApple.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Especiado,
    Strength.Medio
  ),
  new MenuItemLegacy(
    's4',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.tropicalMix.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.tropicalMix.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Frutal,
    Strength.Suave
  ),
  new MenuItemLegacy(
    's5',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.blueberryMint.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.blueberryMint.description',
    undefined,
    Badge.New,
    undefined, undefined, undefined,
    FlavorType.Mentolado,
    Strength.Medio
  ),
  new MenuItemLegacy(
    's6',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.lemonPie.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.lemonPie.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Dulce,
    Strength.Suave
  ),
  new MenuItemLegacy(
    's7',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.passionFruit.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.passionFruit.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Frutal,
    Strength.Medio
  ),
  new MenuItemLegacy(
    's8',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.cola.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.cola.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Dulce,
    Strength.Suave
  ),
  new MenuItemLegacy(
    's9',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.peachIceTea.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.peachIceTea.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Frutal,
    Strength.Suave
  ),
  new MenuItemLegacy(
    's10',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.cinnamonGum.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.cinnamonGum.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Especiado,
    Strength.Fuerte
  ),
  new MenuItemLegacy(
    's11',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.grapeLemon.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.grapeLemon.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Frutal,
    Strength.Medio
  ),
  new MenuItemLegacy(
    's12',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.vanillaCream.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.vanillaCream.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Dulce,
    Strength.Suave
  ),
  new MenuItemLegacy(
    's13',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.mintChocolate.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.mintChocolate.description',
    undefined,
    Badge.Popular,
    undefined, undefined, undefined,
    FlavorType.Mentolado,
    Strength.Medio
  ),
  new MenuItemLegacy(
    's14',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.raspberry.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.raspberry.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Frutal,
    Strength.Medio
  ),
  new MenuItemLegacy(
    's15',
    MenuCategory.Sabores,
    'pages.menu.sabores.items.caramel.name',
    0,
    Currency.EUR,
    'pages.menu.sabores.items.caramel.description',
    undefined,
    undefined,
    undefined, undefined, undefined,
    FlavorType.Dulce,
    Strength.Suave
  ),
];

export const BEBIDAS: MenuItem[] = [
  new MenuItemLegacy(
    'b1',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.alhambraReserva.name',
    3.5,
    Currency.EUR,
    'pages.menu.bebidas.items.alhambraReserva.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Cerveza,
    '330ml'
  ),
  new MenuItemLegacy(
    'b2',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.estrellaDamm.name',
    2.8,
    Currency.EUR,
    'pages.menu.bebidas.items.estrellaDamm.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Cerveza,
    '330ml'
  ),
  new MenuItemLegacy(
    'b3',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.cocaCola.name',
    2.5,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Refresco,
    '330ml'
  ),
  new MenuItemLegacy(
    'b4',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.fanta.name',
    2.5,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Refresco,
    '330ml'
  ),
  new MenuItemLegacy(
    'b5',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.sprite.name',
    2.5,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Refresco,
    '330ml'
  ),
  new MenuItemLegacy(
    'b6',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.teMoruno.name',
    3,
    Currency.EUR,
    'pages.menu.bebidas.items.teMoruno.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Te,
    undefined
  ),
  new MenuItemLegacy(
    'b7',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.aguaMineral.name',
    2,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Agua,
    '500ml'
  ),
  new MenuItemLegacy(
    'b8',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.redbull.name',
    3.5,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Refresco,
    '250ml'
  ),
  new MenuItemLegacy(
    'b9',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.tonica.name',
    2.5,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Refresco,
    '200ml'
  ),
  new MenuItemLegacy(
    'b10',
    MenuCategory.Bebidas,
    'pages.menu.bebidas.items.zumoNaranja.name',
    3.5,
    Currency.EUR,
    undefined,
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    DrinkType.Refresco,
    undefined
  ),
];

export const COCTELES: MenuItem[] = [
  new MenuItemLegacy(
    'c1',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.mojito.name',
    8,
    Currency.EUR,
    'pages.menu.cocteles.items.mojito.description',
    undefined,
    Badge.Popular,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Ron blanco', 'Menta', 'Lima', 'Azúcar', 'Soda'],
    AlcoholContent.Medio
  ),
  new MenuItemLegacy(
    'c2',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.cosmopolitan.name',
    9,
    Currency.EUR,
    'pages.menu.cocteles.items.cosmopolitan.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Vodka', 'Cointreau', 'Zumo de arándanos', 'Lima'],
    AlcoholContent.Medio
  ),
  new MenuItemLegacy(
    'c3',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.ginTonic.name',
    10,
    Currency.EUR,
    'pages.menu.cocteles.items.ginTonic.description',
    undefined,
    Badge.Signature,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Gin premium', 'Tónica', 'Botánicos'],
    AlcoholContent.Medio
  ),
  new MenuItemLegacy(
    'c4',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.margarita.name',
    8.5,
    Currency.EUR,
    'pages.menu.cocteles.items.margarita.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Tequila', 'Cointreau', 'Lima', 'Sal'],
    AlcoholContent.Medio
  ),
  new MenuItemLegacy(
    'c5',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.pinaColada.name',
    9,
    Currency.EUR,
    'pages.menu.cocteles.items.pinaColada.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Ron', 'Crema de coco', 'Zumo de piña'],
    AlcoholContent.Medio
  ),
  new MenuItemLegacy(
    'c6',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.goatSpecial.name',
    12,
    Currency.EUR,
    'pages.menu.cocteles.items.goatSpecial.description',
    undefined,
    Badge.Signature,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Ingredientes secretos'],
    AlcoholContent.Alto
  ),
  new MenuItemLegacy(
    'c7',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.oldFashioned.name',
    10,
    Currency.EUR,
    'pages.menu.cocteles.items.oldFashioned.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Bourbon', 'Angostura', 'Azúcar', 'Naranja'],
    AlcoholContent.Alto
  ),
  new MenuItemLegacy(
    'c8',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.aperolSpritz.name',
    8,
    Currency.EUR,
    'pages.menu.cocteles.items.aperolSpritz.description',
    undefined,
    Badge.Popular,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Aperol', 'Prosecco', 'Soda'],
    AlcoholContent.Bajo
  ),
  new MenuItemLegacy(
    'c9',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.negroni.name',
    9.5,
    Currency.EUR,
    'pages.menu.cocteles.items.negroni.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Gin', 'Campari', 'Vermut rojo'],
    AlcoholContent.Alto
  ),
  new MenuItemLegacy(
    'c10',
    MenuCategory.Cocteles,
    'pages.menu.cocteles.items.espressoMartini.name',
    9,
    Currency.EUR,
    'pages.menu.cocteles.items.espressoMartini.description',
    undefined,
    Badge.New,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    ['Vodka', 'Licor de café', 'Espresso'],
    AlcoholContent.Medio
  ),
];

export const COMIDA: MenuItem[] = [
  new MenuItemLegacy(
    'f1',
    MenuCategory.Comida,
    'pages.menu.comida.items.hummus.name',
    6,
    Currency.EUR,
    'pages.menu.comida.items.hummus.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegan, DietaryType.Vegetarian]
  ),
  new MenuItemLegacy(
    'f2',
    MenuCategory.Comida,
    'pages.menu.comida.items.cheeseBoard.name',
    12,
    Currency.EUR,
    'pages.menu.comida.items.cheeseBoard.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegetarian]
  ),
  new MenuItemLegacy(
    'f3',
    MenuCategory.Comida,
    'pages.menu.comida.items.olives.name',
    4,
    Currency.EUR,
    'pages.menu.comida.items.olives.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegan, DietaryType.Vegetarian, DietaryType.GlutenFree]
  ),
  new MenuItemLegacy(
    'f4',
    MenuCategory.Comida,
    'pages.menu.comida.items.fries.name',
    4.5,
    Currency.EUR,
    'pages.menu.comida.items.fries.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegan, DietaryType.Vegetarian]
  ),
  new MenuItemLegacy(
    'f5',
    MenuCategory.Comida,
    'pages.menu.comida.items.nachos.name',
    8,
    Currency.EUR,
    'pages.menu.comida.items.nachos.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegetarian]
  ),
  new MenuItemLegacy(
    'f6',
    MenuCategory.Comida,
    'pages.menu.comida.items.wings.name',
    9,
    Currency.EUR,
    'pages.menu.comida.items.wings.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined
  ),
  new MenuItemLegacy(
    'f7',
    MenuCategory.Comida,
    'pages.menu.comida.items.babaGanoush.name',
    6.5,
    Currency.EUR,
    'pages.menu.comida.items.babaGanoush.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegan, DietaryType.Vegetarian]
  ),
  new MenuItemLegacy(
    'f8',
    MenuCategory.Comida,
    'pages.menu.comida.items.mixedNuts.name',
    5,
    Currency.EUR,
    'pages.menu.comida.items.mixedNuts.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegan, DietaryType.Vegetarian, DietaryType.GlutenFree]
  ),
  new MenuItemLegacy(
    'f9',
    MenuCategory.Comida,
    'pages.menu.comida.items.bruschetta.name',
    7,
    Currency.EUR,
    'pages.menu.comida.items.bruschetta.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegetarian]
  ),
  new MenuItemLegacy(
    'f10',
    MenuCategory.Comida,
    'pages.menu.comida.items.arabicBread.name',
    3.5,
    Currency.EUR,
    'pages.menu.comida.items.arabicBread.description',
    undefined, undefined,
    undefined, undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    [DietaryType.Vegan, DietaryType.Vegetarian]
  ),
];

